### Get the first page of synonyms with a limit of 20 (default value)
GET http://localhost:8080/words/synonyms



### Get the last page of synonyms with a limit of 50
GET http://localhost:8080/words/synonyms?
    cursor=5f5cddd9-1064-46e3-8070-d1a672b9adce
    &limit=50

